# Generated by Django 5.0 on 2023-12-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='candle',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='candle',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='candle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candle',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='candle',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
